sudo: false

language: python
python:
  - 2.7

# use cache for pip (especially for scipy)
cache:
    pip: true
    custom_install: true

virtualenv:
    system_site_packages: true

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    #don't install LaTeX (yet)
    #- texlive-extra-utils
    #- texlive-latex-extra
    - dvipng
    #- libfreetype6
    - python-qt4
    #don't install ROOT yet
    #- root-system

before_install:
  # create cache directory if none exists
  - mkdir -p $HOME/.cache/pip/wheels
  # upgrade pip to latest version
  - pip install --upgrade pip
  # get and build scipy, if not already cached
  - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
  # install from cache
  - pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy
  # install other dependencies
  - pip install pytest
  - pip install numpy
  - pip install matplotlib
  - pip install --upgrade iminuit
  # check success
  - python -c "import numpy"
  - python -c "import scipy"
  - python -c "import matplotlib"

install:
  - pip install -e .

script:
  - python setup.py test
